Updated to AlmaLinux 9
osuosl-cookbooks/dnf-automatic pull request #10
Opened 2023-11-29 18:53 UTC by GrantAOConnor

2023-11-29 19:16 UTC, ramereth requested changes

2023-11-29 19:16 UTC, ramereth commented on CHANGELOG.md
> +
Please remove this. Our automated system automatically updates this when we merge this.

2023-11-29 19:16 UTC, ramereth commented on metadata.rb
> +supports         'almalinux', '~> 9.0'
Please keep 8.0 listed and only add 9.0

2023-11-29 19:16 UTC, ramereth commented on recipes/default.rb
> +if node['platform_version'].to_i < 9
This needs to stay as this still works on EL8

2023-11-29 19:16 UTC, ramereth commented on spec/spec_helper.rb
> +  version: '9',
Keep ALMA_8 but add ALMA_9

2023-11-29 21:04 UTC, ramereth approved these changes
Patch bump.

2024-02-09 19:30 UTC, ramereth commented
!bump patch ~

2024-02-09 19:30 UTC, merged

2024-02-09 19:30 UTC, osuosl-manatee commented
Jenkins has merged this PR into `master` and has automatically performed a patch-level version bump to v2.0.5.  Have a nice day!